### ISSUE TITLE
time_rotating.service_account_rotation : Provider produced inconsistent result after apply 

### ISSUE THREAD

**Issue by leonmsdev** [hashicorp/terraform-provider-time#125]
### Terraform CLI and Provider Versions

Installed hashicorp/time` v0.8.0` (signed by HashiCorp)

```
terraform {
  required_version = ">= 0.15"
}
```

### Terraform Configuration

```terraform
resource "time_rotating" "service_account_rotation" {
  rotation_days = 30
}

resource "google_service_account" "docker" {
  account_id   = "docker"
  display_name = "Used for docker"
}

resource "google_service_account_key" "docker_key" {
  count              = terraform.workspace == "live" ? 1 : 0
  service_account_id = google_service_account.docker[0].account_id
  public_key_type    = "TYPE_X509_PEM_FILE"

  keepers = {
    rotation_time = time_rotating.service_account_rotation.rotation_rfc3339
  }
}
```

### Expected Behavior

We changed our existing `time_rotation` ressource from `rotation_days = 30` to `rotation_days = 1`.
As shown in the terraform plan, we expect that the time rotation would change from 30 to 1.

```
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  ~ update in-place
Terraform will perform the following actions:
  # time_rotating.service_account_rotation will be updated in-place
  ~ resource "time_rotating" "service_account_rotation" {
        id               = "2022-09-05T05:55:07Z"
      ~ rotation_days    = 30 -> 1
        # (9 unchanged attributes hidden)
    }
```

### Actual Behavior

The `terraform apply` fails when changing the `rotation_days` from 30 days to 1 day.
The same error appears when changing from `rotation_days` to `rotation_hours`.

```
$ terraform init
... 
load modules
...
Terraform has been successfully initialized!
You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.
If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
$ terraform workspace select ${STAGE}
Switched to workspace "dev".
$ terraform apply -input=false ${STAGE}-planfile

time_rotating.service_account_rotation: Modifying... [id=2022-09-05T05:55:07Z]
╷
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to time_rotating.service_account_rotation, provider
│ "provider[\"registry.terraform.io/hashicorp/time\"]" produced an unexpected
│ new value: Root resource was present, but now absent.
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.

Cleaning up project directory and file based variables
00:01
ERROR: Job failed: command terminated with exit code 

```

### Steps to Reproduce

Assign time_rotation to Service Account Key
1. `terraform init`
2. `terraform apply`

After the first successful apply, change the value of `rotation_days`.
1. `terraform init`
2. `terraform apply`

Terraform should then fail with the same error message.

### How much impact is this issue causing?

Medium

### Additional Information

- Our resources are created inside GCP
- Terraform apply runs inside Gitlab CI/CD

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Noel-Jones** [comment]
I *think* it is line 422:

````
func (t timeRotatingResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state timeRotatingModelV0

	diags := req.Plan.Get(ctx, &plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	diags = req.Plan.Get(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
````

It looks to be filling in the state and the plan from the plan, then it will determine there is no change so it will not calculate the update during the apply. I'll see if I can create a PR ...

**Comment by SBGoods** [comment]
Hi @leonmsdev, thank you for raising this issue and we apologize for the delay. We recently migrated the Time provider from Terraform Plugin SDKv2 to Terraform Plugin Framework and solved a similar issue #133 with the time_rotating resource that was released in v0.9.1. Can you upgrade the Time Provider to v0.9.1 and see if you can replicate the same issue in that version?

Please reach out if you have any further questions!

**Comment by SBGoods** [comment]
Hi @leonmsdev, since we haven't heard back from you in a while, I'm going to close this issue for now. If you are still running into issues with this, please feel free to reach out and open another issue.

**Comment by leonmsdev** [comment]
Hello @SBGoods, thanks for your help.
Updating the time_rotating version  to latest fixed the problem for me.
