### ISSUE TITLE
Error: The terraform-provider-time_v0.9.1_x5 plugin crashed

### ISSUE THREAD

**Issue by jeenadeepak** [hashicorp/terraform-provider-time#143]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* time_XXXXX

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Panic Output
╷
│ Error: Unrecognized remote plugin message: 
│ 
│ This usually means that the plugin is either invalid or simply
│ needs to be recompiled to support the latest protocol.
│ 
│ 
╵
╷
│ Error: Unrecognized remote plugin message: 
│ 
│ This usually means that the plugin is either invalid or simply
│ needs to be recompiled to support the latest protocol.
│ 
│ 
╵
╷
│ Error: Unrecognized remote plugin message: 
│ 
│ This usually means that the plugin is either invalid or simply
│ needs to be recompiled to support the latest protocol.
│ 
│ 
╵

Stack trace from the terraform-provider-null_v3.2.1_x5 plugin:

fatal error: out of memory allocating heap arena map

runtime stack:
runtime.throw({0xb0581b?, 0x0?})
	runtime/panic.go:992 +0x71 fp=0x7fff4d4f30f8 sp=0x7fff4d4f30c8 pc=0x433fd1
runtime.(*mheap).sysAlloc(0x100c360, 0x0?)
	runtime/malloc.go:743 +0x307 fp=0x7fff4d4f3190 sp=0x7fff4d4f30f8 pc=0x40c507
runtime.(*mheap).grow(0x100c360, 0x0?)
	runtime/mheap.go:1358 +0x73 fp=0x7fff4d4f31f0 sp=0x7fff4d4f3190 pc=0x4273d3
runtime.(*mheap).allocSpan(0x100c360, 0x1, 0x0, 0x32)
	runtime/mheap.go:1170 +0x171 fp=0x7fff4d4f3268 sp=0x7fff4d4f31f0 pc=0x426e71
runtime.(*mheap).alloc.func1()
	runtime/mheap.go:912 +0x65 fp=0x7fff4d4f32b0 sp=0x7fff4d4f3268 pc=0x426965
runtime.(*mheap).alloc(0x0?, 0x0?, 0x0?)
	runtime/mheap.go:906 +0x65 fp=0x7fff4d4f32f8 sp=0x7fff4d4f32b0 pc=0x4268a5
runtime.(*mcentral).grow(0x0?)
	runtime/mcentral.go:244 +0x5b fp=0x7fff4d4f3340 sp=0x7fff4d4f32f8 pc=0x4176db
runtime.(*mcentral).cacheSpan(0x101eb20)
	runtime/mcentral.go:164 +0x30f fp=0x7fff4d4f3398 sp=0x7fff4d4f3340 pc=0x41750f
runtime.(*mcache).refill(0x7efd1de4b108, 0x32)
	runtime/mcache.go:162 +0xaf fp=0x7fff4d4f33d0 sp=0x7fff4d4f3398 pc=0x416b8f
runtime.(*mcache).nextFree(0x7efd1de4b108, 0x32)
	runtime/malloc.go:886 +0x85 fp=0x7fff4d4f3418 sp=0x7fff4d4f33d0 pc=0x40ca65
runtime.mallocgc(0x1e0, 0xa04a80, 0x1)
	runtime/malloc.go:1085 +0x4e5 fp=0x7fff4d4f3490 sp=0x7fff4d4f3418 pc=0x40d0e5
runtime.newobject(0x7fff4d4f4be5?)
	runtime/malloc.go:1259 +0x27 fp=0x7fff4d4f34b8 sp=0x7fff4d4f3490 pc=0x40d627
internal/cpu.doinit()
	internal/cpu/cpu_x86.go:62 +0x25 fp=0x7fff4d4f34f0 sp=0x7fff4d4f34b8 pc=0x4015e5
({0x0, 0x0})
	internal/cpu/cpu.go:123 +0x25 fp=0x7fff4d4f3510 sp=0x7fff4d4f34f0 pc=0x401025
runtime.cpuinit()
	runtime/proc.go:630 +0x111 fp=0x7fff4d4f3550 sp=0x7fff4d4f3510 pc=0x437751
runtime.schedinit()
	runtime/proc.go:692 +0xb0 fp=0x7fff4d4f35b0 sp=0x7fff4d4f3550 pc=0x437850
runtime.rt0_go()
	runtime/asm_amd64.s:322 +0x11c fp=0x7fff4d4f35b8 sp=0x7fff4d4f35b0 pc=0x46181c

Error: The terraform-provider-null_v3.2.1_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

Stack trace from the terraform-provider-cloudinit_v2.2.0_x5 plugin:

fatal error: runtime: out of memory

runtime stack:
runtime.throw(0xbbffda, 0x16)
	/opt/goenv/versions/1.16.0/src/runtime/panic.go:1117 +0x72 fp=0x7ffed361a8f0 sp=0x7ffed361a8c0 pc=0x436412
runtime.sysMap(0xc000000000, 0x4000000, 0x10a0bb0)
	/opt/goenv/versions/1.16.0/src/runtime/mem_linux.go:169 +0xc6 fp=0x7ffed361a930 sp=0x7ffed361a8f0 pc=0x419786
runtime.(*mheap).sysAlloc(0x10878e0, 0x400000, 0x0, 0x0)
	/opt/goenv/versions/1.16.0/src/runtime/malloc.go:729 +0x1e5 fp=0x7ffed361a9d8 sp=0x7ffed361a930 pc=0x40cc25
runtime.(*mheap).grow(0x10878e0, 0x1, 0x0)
	/opt/goenv/versions/1.16.0/src/runtime/mheap.go:1346 +0x85 fp=0x7ffed361aa40 sp=0x7ffed361a9d8 pc=0x428925
runtime.(*mheap).allocSpan(0x10878e0, 0x1, 0x2c00, 0x0)
	/opt/goenv/versions/1.16.0/src/runtime/mheap.go:1173 +0x609 fp=0x7ffed361aac0 sp=0x7ffed361aa40 pc=0x428729
runtime.(*mheap).alloc.func1()
	/opt/goenv/versions/1.16.0/src/runtime/mheap.go:910 +0x59 fp=0x7ffed361ab10 sp=0x7ffed361aac0 pc=0x463159
runtime.(*mheap).alloc(0x10878e0, 0x1, 0x12c, 0x0)
	/opt/goenv/versions/1.16.0/src/runtime/mheap.go:904 +0x85 fp=0x7ffed361ab60 sp=0x7ffed361ab10 pc=0x427cc5
runtime.(*mcentral).grow(0x1099c18, 0x0)
	/opt/goenv/versions/1.16.0/src/runtime/mcentral.go:232 +0x79 fp=0x7ffed361aba8 sp=0x7ffed361ab60 pc=0x418d79
runtime.(*mcentral).cacheSpan(0x1099c18, 0x7ffed361ac58)
	/opt/goenv/versions/1.16.0/src/runtime/mcentral.go:158 +0x2ff fp=0x7ffed361ac00 sp=0x7ffed361aba8 pc=0x418b5f
runtime.(*mcache).refill(0x7fcbc90c7108, 0x2c)
	/opt/goenv/versions/1.16.0/src/runtime/mcache.go:162 +0xaa fp=0x7ffed361ac48 sp=0x7ffed361ac00 pc=0x41806a
runtime.(*mcache).nextFree(0x7fcbc90c7108, 0x7ffed361ac2c, 0x461d25, 0x7ffed361ace8, 0x40e73e)
	/opt/goenv/versions/1.16.0/src/runtime/malloc.go:882 +0x8d fp=0x7ffed361ac80 sp=0x7ffed361ac48 pc=0x40d48d
runtime.mallocgc(0x178, 0xbb12e0, 0x7ffed361ad01, 0x7ffed361ad68)
	/opt/goenv/versions/1.16.0/src/runtime/malloc.go:1069 +0x850 fp=0x7ffed361ad08 sp=0x7ffed361ac80 pc=0x40de90
runtime.newobject(0xbb12e0, 0x461ce0)
	/opt/goenv/versions/1.16.0/src/runtime/malloc.go:1177 +0x38 fp=0x7ffed361ad38 sp=0x7ffed361ad08 pc=0x40e0f8
runtime.malg(0x8000, 0x0)
	/opt/goenv/versions/1.16.0/src/runtime/proc.go:3944 +0x31 fp=0x7ffed361ad78 sp=0x7ffed361ad38 pc=0x4413b1
runtime.mpreinit(0x1070360)
	/opt/goenv/versions/1.16.0/src/runtime/os_linux.go:355 +0x29 fp=0x7ffed361ad98 sp=0x7ffed361ad78 pc=0x432ea9
runtime.mcommoninit(0x1070360, 0xffffffffffffffff)
	/opt/goenv/versions/1.16.0/src/runtime/proc.go:744 +0xf7 fp=0x7ffed361ade0 sp=0x7ffed361ad98 pc=0x43a2d7
runtime.schedinit()
	/opt/goenv/versions/1.16.0/src/runtime/proc.go:637 +0xaf fp=0x7ffed361ae40 sp=0x7ffed361ade0 pc=0x439e4f
runtime.rt0_go(0x7ffed361ae78, 0x1, 0x7ffed361ae78, 0x0, 0x0, 0x1, 0x7ffed361d001, 0x0, 0x7ffed361d0ab, 0x7ffed361d0f4, ...)
	/opt/goenv/versions/1.16.0/src/runtime/asm_amd64.s:220 +0x125 fp=0x7ffed361ae48 sp=0x7ffed361ae40 pc=0x46a1e5

Error: The terraform-provider-cloudinit_v2.2.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

Stack trace from the terraform-provider-time_v0.9.1_x5 plugin:

fatal error: out of memory allocating heap arena map

runtime stack:
runtime.throw({0xb1160e?, 0x0?})
	runtime/panic.go:992 +0x71 fp=0x7fff889bec28 sp=0x7fff889bebf8 pc=0x433fd1
runtime.(*mheap).sysAlloc(0x101d680, 0x0?)
	runtime/malloc.go:743 +0x307 fp=0x7fff889becc0 sp=0x7fff889bec28 pc=0x40c507
runtime.(*mheap).grow(0x101d680, 0x0?)
	runtime/mheap.go:1358 +0x73 fp=0x7fff889bed20 sp=0x7fff889becc0 pc=0x4273d3
runtime.(*mheap).allocSpan(0x101d680, 0x1, 0x0, 0x32)
	runtime/mheap.go:1170 +0x171 fp=0x7fff889bed98 sp=0x7fff889bed20 pc=0x426e71
runtime.(*mheap).alloc.func1()
	runtime/mheap.go:912 +0x65 fp=0x7fff889bede0 sp=0x7fff889bed98 pc=0x426965
runtime.(*mheap).alloc(0x0?, 0x0?, 0x0?)
	runtime/mheap.go:906 +0x65 fp=0x7fff889bee28 sp=0x7fff889bede0 pc=0x4268a5
runtime.(*mcentral).grow(0x0?)
	runtime/mcentral.go:244 +0x5b fp=0x7fff889bee70 sp=0x7fff889bee28 pc=0x4176db
runtime.(*mcentral).cacheSpan(0x102fe40)
	runtime/mcentral.go:164 +0x30f fp=0x7fff889beec8 sp=0x7fff889bee70 pc=0x41750f
runtime.(*mcache).refill(0x7f5c1a08c108, 0x32)
	runtime/mcache.go:162 +0xaf fp=0x7fff889bef00 sp=0x7fff889beec8 pc=0x416b8f
runtime.(*mcache).nextFree(0x7f5c1a08c108, 0x32)
	runtime/malloc.go:886 +0x85 fp=0x7fff889bef48 sp=0x7fff889bef00 pc=0x40ca65
runtime.mallocgc(0x1e0, 0xa106a0, 0x1)
	runtime/malloc.go:1085 +0x4e5 fp=0x7fff889befc0 sp=0x7fff889bef48 pc=0x40d0e5
runtime.newobject(0x7fff889c1be5?)
	runtime/malloc.go:1259 +0x27 fp=0x7fff889befe8 sp=0x7fff889befc0 pc=0x40d627
internal/cpu.doinit()
	internal/cpu/cpu_x86.go:62 +0x25 fp=0x7fff889bf020 sp=0x7fff889befe8 pc=0x4015e5
({0x0, 0x0})
	internal/cpu/cpu.go:123 +0x25 fp=0x7fff889bf040 sp=0x7fff889bf020 pc=0x401025
runtime.cpuinit()
	runtime/proc.go:630 +0x111 fp=0x7fff889bf080 sp=0x7fff889bf040 pc=0x437751
runtime.schedinit()
	runtime/proc.go:692 +0xb0 fp=0x7fff889bf0e0 sp=0x7fff889bf080 pc=0x437850
runtime.rt0_go()
	runtime/asm_amd64.s:322 +0x11c fp=0x7fff889bf0e8 sp=0x7fff889bf0e0 pc=0x46181c

Error: The terraform-provider-time_v0.9.1_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by austinvalle** [comment]
Hi there @jeenadeepak 👋🏻, sorry for the delayed response on this. This appears to be an out-of-memory issue and not necessarily just scoped to the `time` provider. As I haven't seen any comments related to this being a bug for the `time` provider specifically, I'm going to close this issue.

If you're still running into memory errors that you believe are specific to this provider, feel free to create a new issue, thanks!
