### ISSUE TITLE
time_sleep context deadline exceeded after 20m

### ISSUE THREAD

**Issue by frankgu968** [hashicorp/terraform-provider-time#19]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.13.5

provider registry.terraform.io/hashicorp/time v0.6.0

### Affected Resource(s)

* time_sleep

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp

resource "time_sleep" "wait_for_peering_active" {
  create_duration = "45m"
}
```

### Debug Output

```
2020/11/05 06:13:31 [DEBUG] module.gcp.time_sleep.wait_for_peering_active: apply errored, but we're indicating that via the Error pointer rather than returning it: context deadline exceeded
2020/11/05 06:13:31 [TRACE] eval: *terraform.EvalMaybeTainted
2020/11/05 06:13:31 [TRACE] EvalMaybeTainted: module.gcp.time_sleep.wait_for_peering_active encountered an error during creation, so it is now marked as tainted
2020/11/05 06:13:31 [TRACE] eval: *terraform.EvalWriteState
2020/11/05 06:13:31 [TRACE] EvalWriteState: removing state object for module.gcp.time_sleep.wait_for_peering_active
2020/11/05 06:13:31 [TRACE] eval: *terraform.EvalApplyProvisioners
2020/11/05 06:13:31 [TRACE] EvalApplyProvisioners: time_sleep.wait_for_peering_active has no state, so skipping provisioners
2020/11/05 06:13:31 [TRACE] eval: *terraform.EvalMaybeTainted
2020/11/05 06:13:31 [TRACE] EvalMaybeTainted: module.gcp.time_sleep.wait_for_peering_active encountered an error during creation, so it is now marked as tainted
2020/11/05 06:13:31 [TRACE] eval: *terraform.EvalWriteState
2020/11/05 06:13:31 [TRACE] EvalWriteState: removing state object for module.gcp.time_sleep.wait_for_peering_active
2020/11/05 06:13:31 [TRACE] eval: *terraform.EvalIf
2020/11/05 06:13:31 [TRACE] eval: *terraform.EvalIf
2020/11/05 06:13:31 [TRACE] eval: *terraform.EvalWriteDiff
2020/11/05 06:13:31 [TRACE] eval: *terraform.EvalApplyPost
2020/11/05 06:13:31 [ERROR] eval: *terraform.EvalApplyPost, err: context deadline exceeded
2020/11/05 06:13:31 [ERROR] eval: *terraform.EvalSequence, err: context deadline exceeded
2020/11/05 06:13:31 [TRACE] [walkApply] Exiting eval tree: module.gcp.time_sleep.wait_for_peering_active
```

### Expected Behavior

time_sleep should be able  to sleep for arbitrary amounts of time within the terraform default timeout limit.

### Actual Behavior

Getting an "Error: context deadline exceeded" after sleeping for 20 minutees

### Steps to Reproduce

1. `terraform apply`

**Comment by bflad** [comment]
Hi @frankgu968 👋  Thank you for reporting this and sorry you ran into trouble here. Indeed the current implementation would currently have this issue as there is a default timeout of 20 minutes imposed on Terraform resources in this situation. Our solution here will either be removing that default timeout with a resource code fix or potentially deprecating the duration arguments in preference of the "standard" [Terraform resource customizable timeouts](https://www.terraform.io/docs/language/resources/syntax.html#operation-timeouts).

In the meantime, you should be able to use the link provided above to workaround this:

```terraform
resource "time_sleep" "wait_for_peering_active" {
  create_duration = "45m"

  timeouts {
    create = "46m" # Must be configured with a higher value to prevent the error
  }
}
```

**Comment by frankgu968** [comment]
Thanks for the suggestion! We worked around the issue already but will give your solution a try if we ever run into the issue again.

**Comment by bflad** [comment]
I'm actually going to keep this open as it is a bug we should fix so workarounds are not necessary. 👍
