### ISSUE TITLE
Upgrade Provider - Create/Update provider design, readme, contributing and support docs

### ISSUE THREAD

**Issue by kmoe** [hashicorp/terraform-provider-time#50]
Maintenance of the standard library providers prioritises stability and correctness relative to the provider's intended feature set. Create a design document describing this feature set, and any other design considerations which influence the architecture of the provider and what can and cannot be added to it.

As part of the [utility provider upgrade](https://docs.google.com/document/d/1_zUbW-PYvsr0IKoO22GhANcmiaL9OxAwYCLkHomL2-0/edit) guidance in the form of `CONTRIBUTING.md`, `DESIGN.md`, README.md` and `SUPPORT.md` either needs to be added or updated. There are examples in the _tls_ provider:
- [CONTRIBUTING.md](https://github.com/hashicorp/terraform-provider-tls/blob/main/.github/CONTRIBUTING.md)
- [DESIGN.md](https://github.com/hashicorp/terraform-provider-tls/blob/main/DESIGN.md)
- [README.md](https://github.com/hashicorp/terraform-provider-tls/blob/main/README.md)
- [SUPPORT.md](https://github.com/hashicorp/terraform-provider-tls/blob/main/.github/SUPPORT.md)

**Comment by SBGoods** [comment]
In order to keep the scope of this issue reasonable, I've created a separate issue for creating the design doc. See #113.
