### ISSUE TITLE
time_static with variable rfc3339 attribute is always recreated

### ISSUE THREAD

**Issue by mark-00** [hashicorp/terraform-provider-time#61]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
```
terraform -v
Terraform v1.0.8
on linux_amd64
+ provider registry.terraform.io/hashicorp/time v0.7.2
```

### Affected Resource(s)

* time_static

### Terraform Configuration Files

```hcl
resource "time_static" "now" {
  rfc3339 = timestamp()
}


```

### Expected Behavior

First apply resource time_static.now is created
consecutive applies should not change resources

### Actual Behavior

The resources time_static.now is always replaced
```
terraform apply
time_static.now: Refreshing state... [id=2022-01-04T12:39:57Z]

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
-/+ destroy and then create replacement

Terraform will perform the following actions:

  # time_static.now must be replaced
-/+ resource "time_static" "now" {
      ~ day     = 4 -> (known after apply)
      ~ hour    = 12 -> (known after apply)
      ~ id      = "2022-01-04T12:39:57Z" -> (known after apply)
      ~ minute  = 39 -> (known after apply)
      ~ month   = 1 -> (known after apply)
      ~ rfc3339 = "2022-01-04T12:39:57Z" -> (known after apply) # forces replacement
      ~ second  = 57 -> (known after apply)
      ~ unix    = 1641299997 -> (known after apply)
      ~ year    = 2022 -> (known after apply)
    }

Plan: 1 to add, 0 to change, 1 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value:
````
### Steps to Reproduce

1. `terraform apply`
2. `terraform apply`

### References

* #0000

**Comment by mark-00** [comment]
Can you please tell me why this is marked invalid ?

**Comment by bflad** [comment]
Hi @mark-00 👋  Thank you for submitting this and sorry you ran into trouble here.

The [`timestamp()` function](https://www.terraform.io/language/functions/timestamp) in Terraform is special as it generates a different value over time. In particular:

> The result of this function will change every second, so using this function directly with resource attributes will cause a diff to be detected on every Terraform run. We do not recommend using this function in resource attributes, but in rare cases it can be used in conjunction with the ignore_changes lifecycle meta-argument to take the timestamp only on initial creation of the resource.

If you intended to only apply the `timestamp()` function value once for the creation of the `time_static` resource, then a resource configuration like the following should ignore the value changes:

```terraform
resource "time_static" "now" {
  rfc3339 = timestamp()

  lifecycle {
    ignore_changes = [rfc3339]
  }
}
```

It is probably worth mentioning though that the above is essentially equivalent to the below:

```terraform
resource "time_static" "now" {}
```

Which is likely much more common in practice. Hope this helps!

Please note: We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. Thanks again.

**Comment by mark-00** [comment]
functionally the code below is not exactly the same because I have no control over the base time
```
resource "time_static" "now" {}
```

Consider using 2 time resources that use the same rfc3339. I can now safely compare them. My real life scenario is a bit more complex but the lifecyle gets me where I want. Thanks for the quick response

```
locals {
  now =timestamp()
}

resource "time_static" "now1" {
  rfc3339 = local.now
  lifecycle {
    ignore_changes = [rfc3339]
  }
}

resource "time_static" "now2" {
  rfc3339 = local.now 
  lifecycle {
    ignore_changes = [rfc3339]
  }
}

locals {
  value = (time_static.now1.rfc3339 == time_static.now2.rfc3339 ) ? 1 : 0
}

```
