### ISSUE TITLE
[Documentation] Update the documentation to describe it clear that it's better to register the time provider first before you using it

### ISSUE THREAD

**Issue by ZPascal** [hashicorp/terraform-provider-time#87]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Please adapt the documentation to make it clear thats it's recommendet to iniitialise the time before you use it. In general it's possible to use the time provider (sleep commands) without initilaisation of the provider but at the end the deletion of the sleep commands is really difficult, because it's necessary to initialise the time provider first, before it's possible to remove the functionality from the Terraform configuration. 

### New or Affected Resource(s)

* time_sleep

### References

* https://registry.terraform.io/providers/hashicorp/time/latest/docs/resources/sleep#delay-create-usage

**Comment by ZPascal** [comment]
Hi @bflad, any chance to update the documentation?

**Comment by bflad** [comment]
Hi @ZPascal 👋  Thanks for raising this. It is a little unclear for me what is being asked. Do you have an example configuration and the (error?) output you are seeing, or can you maybe explain the problem a different way?

In general, it is a Terraform CLI requirement that the [`terraform init` command is always ran before others](https://www.terraform.io/cli/init) to ensure that all the necessary providers are ready for usage with a configuration. There is not anything special with the time provider in this regard.

**Comment by ZPascal** [comment]
Hi @bflad, it's possible to use the sleep commands without an initialisation of the time provider and the following error occurs after the deletion of the sleeps inside the TF code.
```log
Error: Could not satisfy plugin requirements

Plugin reinitialization required. Please run "terraform init".

Plugins are external binaries that Terraform uses to access and manipulate
resources. The configuration provided requires plugins which can't be located,
don't satisfy the version constraints, or are otherwise incompatible.

Terraform automatically discovers provider requirements from your
configuration, including providers used in child modules. To see the
requirements and constraints from each module, run "terraform providers".

Error: provider.time: new or changed plugin executable
```
The error could be solved by adding the `provider "time" {}` setting inside configuration. It would recommend to make it clear, that it's necessary to  initialise the provider beforehand for example as [Azure](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs#example-usage) handle it.

In general, I missed this reference within the time providers [documentation] (https://registry.terraform.io/providers/hashicorp/time/latest/docs#resource-triggers).

**Comment by ZPascal** [comment]
Hi @bflad, do you think it's possible to modify the documentation?

**Comment by ZPascal** [comment]
Hi @bflad, should I prepare a PR to make it tangible.

**Comment by austinvalle** [comment]
Hi all 👋🏻 ,

I'm going to close this issue as this kind of documentation falls more under general Terraform usage rather than `time` provider specific. Terraform already has it documented that it requires a working directory be initialized (as Brian mentioned above): https://developer.hashicorp.com/terraform/cli/init

> _A working directory must be initialized before Terraform can perform any operations in it (like provisioning infrastructure or modifying state)._

Thanks!
